language: python
python:
- 3.5
- 3.6
- 3.7
install: pip install codecov
script: "./scripts/build.sh"
after_success: codecov
deploy:
  provider: pypi
  user: __token__
  password:
    secure: "G0O+wdBmY2RL2qGuVhd0PNl04ICWz+zcSuIFM++W07+nfh/2oacLi140GCYirCnSMAKQLQDBnPlXWKiW3OQkl+7eKzKcDx5EJHcmfL/KsHWQh9GxHk81cnuf1yFvDjpfGHCAUqVgi1h5ZR0dXH0r1lhyhsKPYI0QJ0qWo5ETOMMofP6YGWHydaCcD12XGkIv08qtJGz10R7a5K3iXcTA3vAXb5ObYN5YkgARcM0a3xaN1zR5O7H+RQNU8++W3+SlvAiZ7SxOSA94d1xdlkKLraDZurZ5k0LJYqm+Dvqh25x2NxgT7Lyi60okOqPn/d/DmcYhnk2W7FCS90VQ1qiWry4haqH5iTJYg0n1yV758Nn1pSv9ZYDMpQmVbg+9shysHZSN4ZPdEaUWpkMbtjldGXXiWK0ynfOkmfBM7gELIWDF696vW04BFFVup60+nbp0R5Xo5ZqpW+beb/2O9ImSOlbnsSFtvwVTfw5JToXFwaC3/cTqSRea3f/7LcnVJqYtuRTbBxrnvqWeKi4ZpD3bnfXB0qlZkkzYQiTLp5vPaQPzSA7+YKiFxRAvJXglzQScCmRLwhxFXpLdcagNa1Sn7Ldphm85X/i418SkOZZ7hb8zHB/sC/kR/kfvcvKQEIUCm3QnYYT9gKmyTMfNlVrD1vMIJDgxPZZCSfEry5G4fUM="
  on:
    tags: true
  skip_existing: true
env:
  global:
    - secure: "h3jArT5mOzBl2KkGjX2WYism6NezLhtrBRA5vntxFtyjb4yYNMyngJ7BbI0k9HeceSaModvAFyqoLKtMwd54pTfdIAITmPEDAlmUzQluT7nrrdfD5sQw9pqC2QysV6j8fRa4QTUhJT3mn0JGDrheANMh+fnudE3MLQlQVHLV3abICoHdTIYUu/AxbbjPTk225m1taj8VXJaALVI2NuTxRx5VmMrM1lXYQ0vEvXvV5KsVOtMifexoA9D+Yc3WvMlPPet4WxjV19hHD4m8wJsKQKNQ+9uWSu6WHyxMjw/NidJdf1gy2yf/w0qApykw9VVU75dZG2f3Iave/ijdxJoTHn3Xg3siXjdZPbIddEUYO0JgrPdTReQeLNu6AeWPha1FfxCno5gSrMddOnceh9kyW6ncX0qkzHUunh8qG5had/tKSj3E9e3kpUMYmDZIM3IJen2dUgBt4PhvR93QZdU7wgzFm8KZJIYQW5Kx+HYnTS/wT1IKd1XIma+fcvr1iDQ5z4rbzjnMJJlFCdbthCHYZnBjHfpdrLakXzSxmT+TyaAWcI43ow5Y/ZzU5VypqlwO3GhdoVVeVBhff+0aPCA4LMCLI593P06MYUvfAXwq7hWP786iN3lp+4JvPM0yBCAGurIKnv0d5qDmZwJ/kTfuiJC/8i3hHzEvc7eXBrXQ6KQ="
