language: python
python:
- 3.5
- 3.6
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install:
- pip install coveralls tox-travis
script: tox
after_success: coveralls
deploy:
  provider: pypi
  user: vangorra
  password:
    secure: G+Cs7lrhsCmG8jlRyNO29KCOQlIRth856wUw3SlaU3gjyNFNjIjQWy/bkRguARxDoELF7wQF+GhDqHCS+rXreF4KQAWeZg5xJnqhBzJY04q9MtO5qDGq77y5qyfM7L2DRCzO8V+OrKZXpf3dKMaoGai+BcobAaLEdwzT692XoebbMzbIrfF/9yaSMopReVWW7qt34l+PAyqsgY7Bbm9Wpnoj7j9RNtBCMhuRfZ3wYhM/jZKD6KVyWk+5sNNgFWVwqY8+zRJ2JMjCb2//GjBe15spmuylSCJRgK9o+GizARB11oPFaBE1uaLWs7S3Gz6+fHFNPcf8W2AN56Se5nw1PdAAiSjGwSjvD8oZr/KS9ohF9pNuRnvGrbpNSLx3cB/vBO6U3AqJMBS5CzsZ+cPjJqBGlEKwkOOaIIqOXMaJzgMUlhJyu5Clq7DQ6kWcoH6VJS3pV8uGGzthhheaf+EkyHZwLkpoL+77GVabbbFkoUMn4gVBDBK7zgoptIWUzB0xe+S3t2nEGo/DA63+kuJb7d+SYi5POdp29weXBDKtq6sMvxYuFlQzFr0Lh2G6DxzPyLC30VKFd7yp6XZVm28VT2VjHZYE0UFDwE2+Hjkn073c7WV/2LY66QwnOUfnkL7iBxqCADr/o9Ap0j+XLcRzbG1zPRmti2cvC2vx+KB6T4Y=
  on:
    tags: true
env:
  global:
    secure: Pp2gQZlwcI/Ct1GXPQk7GmX9CSA25FOTkz2vJSoSOUZcvEAZhlD6E0xhY4w6O0yqKXEK3mD0F4aFw38dMNBEJdkrzsRR5Jpx9xMYfEjVz6M7abZFqLoJyPVq0Krzko1aDEnzX2ukX99TGlj0l/6LSRRNpJ201yet2+L/ZJ1xLiEF/pB8VzqyUSs6FiHjX1i3EQG4bsE8mk+woebMR6vqFYbDIzGeArUknu16Ir5s/ks0pqte4LxqLwupsIq2/2OXWPZNTgD7CWGka8nk4dP/elqPLKmLemH0Gw1zBmG7O/jv+94PiSYAuI1BL4fT07l3bU2/rmXAFph8LLdwzFkBOX2nyCAtxia/t/x/OmE28lpBYDYU03m5L1413h3XXpHgcjwRyqL07jHsEoo5pbLGg693M801jAA91qjbs/VsL+m091wtWCzxmbf69EoTlkPttTYOGcFk4iX4S70Hf0/cIrrVfEZvSsiJDzdr1bC8bujRSAnO4p+8Drt7FkZ9XXImXqsE6znkBIucYGP58jfMybXJRSiO0Yztg6oDCiznaUydljXRpDvHJpl8tTL37oc99U08HETV0sbtjitqykk9r3iM5h215m2aaTL4aqTQRR+iGzsK+Da8xgEGuGc0iQ+XXVZBNEo7u4zrbPmW5/Gf3xbLn2gJLAb1XLWOJANyxAs=
