language: python
python:
- 3.5
- 3.6
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install:
- pip install coveralls tox-travis
script: tox
after_success: coveralls
deploy:
  provider: pypi
  user: vangorra
  password:
    secure: uBdJql9NxKhJ6QmlibIWwGVjpy90T/X7QzYNfQ1Uw1vSArgteS3aQxvTNLpOztWCIymSZcE+hPX/djg4312t19MAuysX/jbbTzPj/hBuf9S5hpEhysEnMxCEAnjilJcYvpIGbHsb1UK7Vm34eWnCuVeNcyWMlQcr7AjncGldawVppvFuKpTLA7kvSPUiDU3LH0r8XPDZQUPFihIjrm22LNqi0m2/rg76uWMazDXaLIIkdfP+4HfnN7jRHXp+TZifools+z4+NywvAOVOwE3z7dHeFLjz1Y87WX8xdWrlcPLnc/x04w8gFz9hecumVy2aj982/Re0emIStKHJUfvfOD0AIkF7PBU4V7DWD/3BnVlfBf+3Mc/zeOa53AIrAlZXyp7tqCafOsCeH9jwWihpZkiQgmNrj7257V0iU4HxxQroLC1PcvGQQyOPkzypP/3jFTvqi6S8epvO6a4X8WhnVM8XPLvSO1zjGOQhpuAMhrvIyKjt3Gu9ONMnTWuPCYUieO3NL8d6WNlhG2Xrd9vN5I8mLEhyeJ7Q3uY0Tt3vwwsDwZ4RXyB+4Fg1IOQLXT48WLG+e8kUPfbTuj+XiWyAQq4mhIHtNu/guZpKBEhRzuqiM1gZ5IsR9/cbeilzOLMdkyXHKkoDD7E6kv3M70cruYnVlx0HlMjYJpPQrIdxTI4=
  on:
    tags: true
env:
  global:
    secure: Pp2gQZlwcI/Ct1GXPQk7GmX9CSA25FOTkz2vJSoSOUZcvEAZhlD6E0xhY4w6O0yqKXEK3mD0F4aFw38dMNBEJdkrzsRR5Jpx9xMYfEjVz6M7abZFqLoJyPVq0Krzko1aDEnzX2ukX99TGlj0l/6LSRRNpJ201yet2+L/ZJ1xLiEF/pB8VzqyUSs6FiHjX1i3EQG4bsE8mk+woebMR6vqFYbDIzGeArUknu16Ir5s/ks0pqte4LxqLwupsIq2/2OXWPZNTgD7CWGka8nk4dP/elqPLKmLemH0Gw1zBmG7O/jv+94PiSYAuI1BL4fT07l3bU2/rmXAFph8LLdwzFkBOX2nyCAtxia/t/x/OmE28lpBYDYU03m5L1413h3XXpHgcjwRyqL07jHsEoo5pbLGg693M801jAA91qjbs/VsL+m091wtWCzxmbf69EoTlkPttTYOGcFk4iX4S70Hf0/cIrrVfEZvSsiJDzdr1bC8bujRSAnO4p+8Drt7FkZ9XXImXqsE6znkBIucYGP58jfMybXJRSiO0Yztg6oDCiznaUydljXRpDvHJpl8tTL37oc99U08HETV0sbtjitqykk9r3iM5h215m2aaTL4aqTQRR+iGzsK+Da8xgEGuGc0iQ+XXVZBNEo7u4zrbPmW5/Gf3xbLn2gJLAb1XLWOJANyxAs=
