language: python
python:
- 3.5
- 3.6
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install:
- pip install coveralls tox-travis
script: tox
after_success: coveralls
deploy:
  provider: pypi
  user: __token__
  password:
    secure: wJf8wbgbef0M0++8sgbTpCQJrItLVWZ8HFzq+vCRWdARhXS1Jd5ANZx0r1XTngx77q5e8cH1X6CK0uM2f5cktTrUfFLUBageuxaO4hjzXFagI9yI/biqOjZEQkYeDZpkpoiNRozcz5oMWtiZV2cPLcJbhuwmUaplaIgQxtiuwQed9uF0dKYe53HQKaBhGMj9Xgev8edT73ERTexDNqzWMy2STKPLPOPBOy1qfK3AI6jwZ553hzLSMhWiKzbcGLSSHESjelzSxhm3gsnfLw8OdFYyvvMOUWxt1P26A6vLQYlyUbicW3u20JeuUjbuYz0R++UL8NZJN5g6aCIZFOw87FOzxKTHI1nmZrwbFqJAC39wc9hQvIe8+H5LXRKt56taEzAUwjuSnhVAmUdpPaLFlG4WV+1WNm5Rkzl/rQqprteu/c3VTLPlzxAZ3Iuo4paqCg/hQ1Us01DdzeVU2aT5Rj6SPwFhgYBRuCkR2vzFYMmjlRAyjXc5dUuoJDkSj8DZceHzs8T1MuoMjSoGdXQtWX2Oj+zD8vmaGwtobme2lE6yyqPAjols9kqjP/5Fru6OGxX1qf7D7DSsBRgsNYoJxRRznn4lS5fa/A6mt7nPt6UMSH3xhnSNdtvu3W0t5Y3UXgW64r99gDhMb52UsM0Ce7dkaIQ1uJ3YIAh7R9FtfTE=
  on:
    tags: true
env:
  global:
    secure: Pp2gQZlwcI/Ct1GXPQk7GmX9CSA25FOTkz2vJSoSOUZcvEAZhlD6E0xhY4w6O0yqKXEK3mD0F4aFw38dMNBEJdkrzsRR5Jpx9xMYfEjVz6M7abZFqLoJyPVq0Krzko1aDEnzX2ukX99TGlj0l/6LSRRNpJ201yet2+L/ZJ1xLiEF/pB8VzqyUSs6FiHjX1i3EQG4bsE8mk+woebMR6vqFYbDIzGeArUknu16Ir5s/ks0pqte4LxqLwupsIq2/2OXWPZNTgD7CWGka8nk4dP/elqPLKmLemH0Gw1zBmG7O/jv+94PiSYAuI1BL4fT07l3bU2/rmXAFph8LLdwzFkBOX2nyCAtxia/t/x/OmE28lpBYDYU03m5L1413h3XXpHgcjwRyqL07jHsEoo5pbLGg693M801jAA91qjbs/VsL+m091wtWCzxmbf69EoTlkPttTYOGcFk4iX4S70Hf0/cIrrVfEZvSsiJDzdr1bC8bujRSAnO4p+8Drt7FkZ9XXImXqsE6znkBIucYGP58jfMybXJRSiO0Yztg6oDCiznaUydljXRpDvHJpl8tTL37oc99U08HETV0sbtjitqykk9r3iM5h215m2aaTL4aqTQRR+iGzsK+Da8xgEGuGc0iQ+XXVZBNEo7u4zrbPmW5/Gf3xbLn2gJLAb1XLWOJANyxAs=
