language: python
python:
- 3.5
- 3.6
- 3.7
script: "./scripts/build.sh"
after_success: bash < (curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  user: __token__
  password:
    secure: wJf8wbgbef0M0++8sgbTpCQJrItLVWZ8HFzq+vCRWdARhXS1Jd5ANZx0r1XTngx77q5e8cH1X6CK0uM2f5cktTrUfFLUBageuxaO4hjzXFagI9yI/biqOjZEQkYeDZpkpoiNRozcz5oMWtiZV2cPLcJbhuwmUaplaIgQxtiuwQed9uF0dKYe53HQKaBhGMj9Xgev8edT73ERTexDNqzWMy2STKPLPOPBOy1qfK3AI6jwZ553hzLSMhWiKzbcGLSSHESjelzSxhm3gsnfLw8OdFYyvvMOUWxt1P26A6vLQYlyUbicW3u20JeuUjbuYz0R++UL8NZJN5g6aCIZFOw87FOzxKTHI1nmZrwbFqJAC39wc9hQvIe8+H5LXRKt56taEzAUwjuSnhVAmUdpPaLFlG4WV+1WNm5Rkzl/rQqprteu/c3VTLPlzxAZ3Iuo4paqCg/hQ1Us01DdzeVU2aT5Rj6SPwFhgYBRuCkR2vzFYMmjlRAyjXc5dUuoJDkSj8DZceHzs8T1MuoMjSoGdXQtWX2Oj+zD8vmaGwtobme2lE6yyqPAjols9kqjP/5Fru6OGxX1qf7D7DSsBRgsNYoJxRRznn4lS5fa/A6mt7nPt6UMSH3xhnSNdtvu3W0t5Y3UXgW64r99gDhMb52UsM0Ce7dkaIQ1uJ3YIAh7R9FtfTE=
  on:
    tags: true
  skip_existing: true
env:
  global:
  - secure: Pp2gQZlwcI/Ct1GXPQk7GmX9CSA25FOTkz2vJSoSOUZcvEAZhlD6E0xhY4w6O0yqKXEK3mD0F4aFw38dMNBEJdkrzsRR5Jpx9xMYfEjVz6M7abZFqLoJyPVq0Krzko1aDEnzX2ukX99TGlj0l/6LSRRNpJ201yet2+L/ZJ1xLiEF/pB8VzqyUSs6FiHjX1i3EQG4bsE8mk+woebMR6vqFYbDIzGeArUknu16Ir5s/ks0pqte4LxqLwupsIq2/2OXWPZNTgD7CWGka8nk4dP/elqPLKmLemH0Gw1zBmG7O/jv+94PiSYAuI1BL4fT07l3bU2/rmXAFph8LLdwzFkBOX2nyCAtxia/t/x/OmE28lpBYDYU03m5L1413h3XXpHgcjwRyqL07jHsEoo5pbLGg693M801jAA91qjbs/VsL+m091wtWCzxmbf69EoTlkPttTYOGcFk4iX4S70Hf0/cIrrVfEZvSsiJDzdr1bC8bujRSAnO4p+8Drt7FkZ9XXImXqsE6znkBIucYGP58jfMybXJRSiO0Yztg6oDCiznaUydljXRpDvHJpl8tTL37oc99U08HETV0sbtjitqykk9r3iM5h215m2aaTL4aqTQRR+iGzsK+Da8xgEGuGc0iQ+XXVZBNEo7u4zrbPmW5/Gf3xbLn2gJLAb1XLWOJANyxAs=
  - secure: JyY86insDUZLYMzY+ZPs/23UTpG/hFNJTm4+T4MlwhaTbvYWdZp5WWtx5LRP4JUpbtM4jC2XpoaO38bFQurpTtCC4sRP6jl+eKy01z+aagSfIuEJfLsdMC2wSaAS43rHouqYCi2ACDDddXTSWXuy54Wq/vKzlaMmLPrK+/RSAzbOqhcP0COG/x2cOQMlj6rfCQ11s4xkijCEn5n/bGcuZ74uIOJ0KRc3UwNBlgWich/MwA9q+Aas1Qf6fRx4N/GQ2rlcOmtpAne1MDHrPCwZtwW9eSewzQ1LuWc5efygG9SO58ox/M2Zdd6cC6dNEDIdBpKB2fca7kmdoHc6xjjzWrSx36NROEAEoKxvK3PAKUC476hDBeKDvkS2IVerqIm9hAS69LGs9Pd1BK0XPogcjomKmicgti8CyuwRRDcRE8ZmK9PUUBpiVZylraBO0Vgshk1ANb+OYwXIRqVAhiOgnqwzg4DkNmlpRqdknOd1v52IVTOqJR5hZFE+VoA2Eqia6tqL9gwIZdart/rj6tXAxhTarukTJJd2/uNY5bkFdpfTCYnh/WNzkVzm7M8uTNW/uKrqQ2q/+CFF7D+/J2k01AE+pWFQhXdq3osfSLKgdiAwwmPNk26Mw44gu3X6wp5YCJR6iBEjAAPwRE5gcSGk7AFMZHF/DjRu9yWuVzMtFQ4=
