language: python
python:
  - 3.5
  - 3.6
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install coveralls tox-travis
script: tox
after_success: coveralls
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_TOKEN
  on:
    tags: true